In [30]:
import pandas as pd

df = pd.read_excel("../../data/resultat-ansokningsomgang-2024(2).xlsx", sheet_name = 5, skiprows = 5)
df.head(1)

,Utbildningsområde,SUN5 inriktning,SUN5 inriktning namn,Utbildningsnamn,Beslut,Diarienummer,Län,Kommun,Antal kommuner
0,Data/IT,481ab,"Utbildningar till programmerare, spel",Futuregames Game Programmer Specialization,Avslag,MYH 2024/3029,Värmland,Karlstad,2

In [23]:
df.columns

Index(['Utbildningsområde', 'SUN5 inriktning', 'SUN5 inriktning namn',
       'Utbildningsnamn', 'Beslut', 'Diarienummer', 'Län', 'Kommun',
       'Antal kommuner'],
      dtype='object')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842 entries, 0 to 841
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Utbildningsområde     842 non-null    object
 1   SUN5 inriktning       842 non-null    object
 2   SUN5 inriktning namn  842 non-null    object
 3   Utbildningsnamn       842 non-null    object
 4   Beslut                842 non-null    object
 5   Diarienummer          842 non-null    object
 6   Län                   842 non-null    object
 7   Kommun                842 non-null    object
 8   Antal kommuner        842 non-null    int64
dtypes: int64(1), object(8)
memory usage: 59.3+ KB

In [32]:
df.describe()

       Antal kommuner
count      842.000000
mean         3.384798
std          1.486093
min          2.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          9.000000

In [ ]:
df.isnull().sum()