In [11]:
import pandas as pd

df = pd.read_excel("../../data/resultat-ansokningsomgang-2024(2).xlsx", sheet_name = 4, skiprows = 5)
df.head()

,Utbildningsområde,SUN5 inriktning,SUN5 inriktning namn,Utbildningsnamn,Beslut,Diarienummer,Flera kommuner,Antal kommuner,Län,Kommun,...,Sökta utbildningsomgångar,Beviljade utbildningsomgångar,Sökta platser per utbildningsomgång,Sökta platser totalt,Beviljade platser utbildningsomgång 1,Beviljade platser utbildningsomgång 2,Beviljade platser utbildningsomgång 3,Beviljade platser utbildningsomgång 4,Beviljade platser utbildningsomgång 5,Beviljade platser totalt
0,Data/IT,481ab,"Utbildningar till programmerare, spel",AI Programmer,Avslag,MYH 2024/3742,Nej,1,Västerbotten,Umeå,...,3,0,30,90,0,0,0,0,0,0
1,Data/IT,481ab,"Utbildningar till programmerare, spel","Forsbergs, Spelutvecklare – Game Programming",Avslag,MYH 2024/4174,Nej,1,Stockholm,Stockholm,...,3,0,20,60,0,0,0,0,0,0
2,Data/IT,481ab,"Utbildningar till programmerare, spel",Futuregames Game Programmer Specialization,Avslag,MYH 2024/3029,Ja,2,Flera kommuner,Flera kommuner,...,3,0,30,90,0,0,0,0,0,0
3,Data/IT,481ab,"Utbildningar till programmerare, spel",Game Programmer,Avslag,MYH 2024/3425,Nej,1,Blekinge,Karlshamn,...,3,0,25,75,0,0,0,0,0,0
4,Data/IT,481ab,"Utbildningar till programmerare, spel",Spelprogrammerare,Beviljad,MYH 2024/3852,Nej,1,Skåne,Malmö,...,4,3,35,140,35,35,35,0,0,105

In [12]:
df.columns

Index(['Utbildningsområde', 'SUN5 inriktning', 'SUN5 inriktning namn',
       'Utbildningsnamn', 'Beslut', 'Diarienummer', 'Flera kommuner',
       'Antal kommuner', 'Län', 'Kommun', 'YH-poäng', 'Studieform',
       'Studietakt %', 'Typ av examen', 'SeQF nivå', 'Smalt yrkesområde',
       'Utbildningsanordnare administrativ enhet', 'Huvudmannatyp',
       'Sökta utbildningsomgångar', 'Beviljade utbildningsomgångar',
       'Sökta platser per utbildningsomgång', 'Sökta platser totalt',
       'Beviljade platser utbildningsomgång 1',
       'Beviljade platser utbildningsomgång 2',
       'Beviljade platser utbildningsomgång 3',
       'Beviljade platser utbildningsomgång 4',
       'Beviljade platser utbildningsomgång 5', 'Beviljade platser totalt'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1272 entries, 0 to 1271
Data columns (total 28 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Utbildningsområde                         1272 non-null   object
 1   SUN5 inriktning                           1272 non-null   object
 2   SUN5 inriktning namn                      1272 non-null   object
 3   Utbildningsnamn                           1272 non-null   object
 4   Beslut                                    1272 non-null   object
 5   Diarienummer                              1272 non-null   object
 6   Flera kommuner                            1272 non-null   object
 7   Antal kommuner                            1272 non-null   int64
 8   Län                                       1272 non-null   object
 9   Kommun                                    1272 non-null   object
 10  YH-poäng                                  1272 non-null   int64
 11  Studieform                                1272 non-null   object
 12  Studietakt %                              1272 non-null   int64
 13  Typ av examen                             1272 non-null   object
 14  SeQF nivå                                 1252 non-null   float64
 15  Smalt yrkesområde                         1272 non-null   object
 16  Utbildningsanordnare administrativ enhet  1272 non-null   object
 17  Huvudmannatyp                             1272 non-null   object
 18  Sökta utbildningsomgångar                 1272 non-null   int64
 19  Beviljade utbildningsomgångar             1272 non-null   int64
 20  Sökta platser per utbildningsomgång       1272 non-null   int64
 21  Sökta platser totalt                      1272 non-null   int64
 22  Beviljade platser utbildningsomgång 1     1272 non-null   int64
 23  Beviljade platser utbildningsomgång 2     1272 non-null   int64
 24  Beviljade platser utbildningsomgång 3     1272 non-null   int64
 25  Beviljade platser utbildningsomgång 4     1272 non-null   int64
 26  Beviljade platser utbildningsomgång 5     1272 non-null   int64
 27  Beviljade platser totalt                  1272 non-null   int64
dtypes: float64(1), int64(13), object(14)
memory usage: 278.4+ KB

In [14]:
df.describe()

,Antal kommuner,YH-poäng,Studietakt %,SeQF nivå,Sökta utbildningsomgångar,Beviljade utbildningsomgångar,Sökta platser per utbildningsomgång,Sökta platser totalt,Beviljade platser utbildningsomgång 1,Beviljade platser utbildningsomgång 2,Beviljade platser utbildningsomgång 3,Beviljade platser utbildningsomgång 4,Beviljade platser utbildningsomgång 5,Beviljade platser totalt
count,1272.000000,1272.000000,1272.000000,1252.000000,1272.000000,1272.000000,1272.000000,1272.000000,1272.000000,1272.000000,1272.000000,1272.000000,1272.000000,1272.000000
mean,1.432390,362.837264,96.206761,5.017572,3.581761,0.801101,29.937107,106.927673,7.780660,7.744497,7.357704,0.128145,0.069182,23.080189
std,0.979806,89.905455,12.848528,0.131442,0.917312,1.328937,6.374305,34.995530,13.276512,13.263414,13.071800,1.899545,1.475718,39.772265
min,1.000000,100.000000,50.000000,5.000000,1.000000,0.000000,5.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,300.000000,100.000000,5.000000,3.000000,0.000000,25.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,400.000000,100.000000,5.000000,3.000000,0.000000,32.000000,105.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,400.000000,100.000000,5.000000,4.000000,3.000000,35.000000,135.000000,20.000000,20.000000,12.000000,0.000000,0.000000,48.000000
max,9.000000,999.000000,100.000000,6.000000,5.000000,5.000000,35.000000,175.000000,35.000000,35.000000,35.000000,35.000000,35.000000,175.000000

In [15]:
df.isnull().sum()

Utbildningsområde                            0
SUN5 inriktning                              0
SUN5 inriktning namn                         0
Utbildningsnamn                              0
Beslut                                       0
Diarienummer                                 0
Flera kommuner                               0
Antal kommuner                               0
Län                                          0
Kommun                                       0
YH-poäng                                     0
Studieform                                   0
Studietakt %                                 0
Typ av examen                                0
SeQF nivå                                   20
Smalt yrkesområde                            0
Utbildningsanordnare administrativ enhet     0
Huvudmannatyp                                0
Sökta utbildningsomgångar                    0
Beviljade utbildningsomgångar                0
Sökta platser per utbildningsomgång          0
Sökta platser totalt                         0
Beviljade platser utbildningsomgång 1        0
Beviljade platser utbildningsomgång 2        0
Beviljade platser utbildningsomgång 3        0
Beviljade platser utbildningsomgång 4        0
Beviljade platser utbildningsomgång 5        0
Beviljade platser totalt                     0
dtype: int64